tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "github/gh"
tap "tilt-dev/tap"
cask "microsoft-teams"
cask "virtualbox"
cask "signal"
cask "firefox"
cask "font-mononoki"
cask "font-hack-nerd-font"
cask "little-snitch"
cask "signal"
brew "curl"
brew "go"
brew "httpie"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "neovim"
brew "z"
brew "zsh"
brew "gh"
brew "pulumi"
brew "node"
brew "node@10"
brew "npm"
brew "coreutils"
brew "wget"
brew "kubectx"
brew "watch"
brew "docker"
brew "docker-machine"
brew "tree"
brew "graphviz"
brew "switchaudio-osx"
brew "z"
brew "tmux"
brew "kubebuilder"
brew "kind"
brew "kustomize"
brew "kube-ps1"
brew "hadolint"
brew "zplug"
brew "k3d"
brew "gpg"
brew "golangci-lint"
brew "hugo"
brew "tilt"
brew "yarn"
brew "fd"
brew "ripgrep"
brew "the_silver_searcher"
brew "bat"
brew "starship"
brew "gnupg"
brew "yubikey-personalization"
brew "hopenpgp-tools"
brew "ykman"
brew "pinentry-mac"
brew "shellcheck"
brew "git-delta"
mas "Enpass", id: 732710998
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Enpass", id: 732710998
mas "Slack", id: 803453959
mas "Microsoft One Note", id:784801555
